// Plan A — Research Roadmap (v3, TIER-STRUCTURED, FACT-CHECKED)
//
// Every direction has at least: ★ Flagship (Nature / Nat Methods / Nat Biotechnol)
//                              + ★★ Sub-journal (Nat Commun / eLife)
//                              + ★★★ Baseline (Bioinformatics / Cell Reports Methods)
//
// Fact-checked references (Oct 2024 – May 2026, verified via WebSearch 2026-05-13):
//   - ModelAngelo (Jamali et al., Nature 2024): final training = 3,715 map-model pairs
//     (700 was only the manual-curation first iteration)
//   - Cryo-IEF (Nat Methods 2025): 65M particles, 2D-only
//   - DeepQs: 496 paired training samples
//   - DeepEMhancer (Comm Biol 2021): N2N-style, no clean GT
//   - DiffModeler (PMC 2024): DDIM, intermediate resolution
//   - Foldseek (Nat Biotechnol 2024) + Foldseek-Multimer (Nat Methods 2025): atomic only
//   - AlphaFold-Multimer: 60% dimer success rate
//
// IMPORTANT: ChimeraX molmap produces synthetic clean TARGETS that LACK CTF, missing-wedge,
// and anisotropy of real cryo-EM. We treat these as supervised reference signals, not as
// "perfect ground truth".

window.RESEARCH_DATA = {

  // ════════════════════════════════════════════════════════
  // DIRECTION 1: De Novo Atomic Model Building from Density
  // ════════════════════════════════════════════════════════
  model_building: [
    {
      tier: 'flagship',
      tier_label_en: '★ Flagship · Nature / Nat Methods',
      tier_label_zh: '★ 旗舰项目 · Nature / Nat Methods',
      title_en: "Cryo-Builder: An End-to-End Density-to-Model Foundation Model",
      title_zh: "Cryo-Builder：端到端密度→模型基础模型",
      summary_en: "A single multi-modal foundation model that ingests a cryo-EM density volume and jointly outputs atomic coordinates, sequence assignment, secondary structure, and per-residue confidence — the cryo-EM analog of AlphaFold-3.",
      summary_zh: "单一多模态基础模型，输入冷冻电镜密度图，联合输出原子坐标、序列分配、二级结构和每残基置信度 —— 冷冻电镜版的 AlphaFold-3。",
      problem: `<p><strong>AlphaFold-3 (Abramson et al., Nature 2024)</strong> revolutionized sequence→structure prediction with diffusion, but cannot use cryo-EM density as primary input. <strong>ModelAngelo (Jamali et al., Nature 2024, trained on 3,715 map-model pairs)</strong> handles density→model but is a sequential pipeline (CNN → GNN → HMM search) with cascading errors and resolution-dependent performance.</p><p>The field lacks a <em>unified foundation model</em> that learns the joint distribution P(coordinates, sequence, ss, confidence | density). This matters because: (1) it eliminates error propagation; (2) enables end-to-end uncertainty quantification; (3) provides a single model that downstream tasks can fine-tune.</p>`,
      problem_zh: `<p><strong>AlphaFold-3 (Abramson 等, Nature 2024)</strong> 用扩散革命性地解决了序列→结构预测，但无法以冷冻电镜密度为主要输入。<strong>ModelAngelo (Jamali 等, Nature 2024，3,715 对训练数据)</strong> 处理密度→模型但是顺序流水线（CNN → GNN → HMM 搜索），误差累积且分辨率依赖。</p><p>该领域缺少<em>统一基础模型</em>来学习联合分布 P(坐标, 序列, 二级结构, 置信度 | 密度)。这很重要：(1) 消除误差传播；(2) 端到端不确定性量化；(3) 提供下游任务可微调的统一模型。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> ModelAngelo's 3,715 pairs lack multi-task labels (only CA positions); Cryo2Struct2Data has more density but no Q-score truth or domain partitioning. Plan A is the <em>only dataset</em> providing all 8 channels (atom, aa, ss, qscore, chain, domain, interface, segment) on 11K bio-assemblies + PHENIX-validated quality tiers — the exact substrate a unified foundation model requires.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>ModelAngelo 的 3,715 对缺多任务标签（只有 CA 位置）；Cryo2Struct2Data 密度图更多但无 Q-score 真值或结构域划分。Plan A 是<em>唯一</em>在 11K 生物组装体上提供 8 通道（原子、氨基酸、二级结构、Q-score、链、结构域、界面、segment）+ PHENIX 验证质量分档的数据集 —— 统一基础模型所需的精确基础。`,
      approach: `<p><strong>Architecture (3 stages with shared backbone):</strong></p><ul><li><strong>Backbone:</strong> 3D Swin Transformer-V3 + FlashAttention-3, processing density in 8×8×8 Å patches with relative position encoding.</li><li><strong>Stage 1 — Residue localization:</strong> Diffusion-based denoising of a "residue token map" (like AlphaFold-3's atom diffusion).</li><li><strong>Stage 2 — Sequence assignment:</strong> Non-autoregressive transformer, per-position 20-way distribution + confidence.</li><li><strong>Stage 3 — Refinement:</strong> SE(3)-equivariant GNN refines coordinates.</li></ul><p><strong>Training (4-stage curriculum):</strong> (1) 3D MAE pretraining on 11K volumes (50% mask). (2) Multi-task supervised on all 8 Plan A channels. (3) Joint sequence+structure on Gold-tier (Q≥0.65). (4) Fine-tune with Silver/Bronze using Q-score as confidence target.</p>`,
      approach_zh: `<p><strong>架构（共享主干 + 三阶段）：</strong></p><ul><li><strong>主干：</strong>3D Swin Transformer-V3 + FlashAttention-3，density processed as 8×8×8 Å patches。</li><li><strong>阶段 1 — 残基定位：</strong>"残基 token 图"扩散去噪（类似 AlphaFold-3 原子扩散模块）。</li><li><strong>阶段 2 — 序列分配：</strong>非自回归 transformer，每位置 20 类分布 + 置信度。</li><li><strong>阶段 3 — 精修：</strong>SE(3)-等价 GNN 精修原子坐标。</li></ul><p><strong>训练（四阶段课程）：</strong>(1) 11K 密度图 3D MAE 预训练（50% mask）。(2) Plan A 8 通道多任务监督。(3) Gold 档（Q≥0.65）联合序列+结构训练。(4) Silver/Bronze 数据微调，Q-score 作为置信度目标。</p>`,
      key_challenges: `<p><strong>Challenge 1: Compute cost (4×8 H100 cluster, 4-6 weeks). Solution:</strong> Patch-level masking reduces memory 75%; mixed precision + activation checkpointing; staged freeze-unfreeze.</p><p><strong>Challenge 2: Non-autoregressive sequence generation instability. </strong><strong>Solution:</strong>(a) ESM-2 pretrained token token initialization；(b) iterative refinement（similar to AF-3）；(c) HMM search as post-processing.</p><p><strong>Challenge 3: Complex multi-task evaluation. Solution:</strong> Composite score (CA RMSD + seq. identity + completeness + Q-score correlation), head-to-head vs. ModelAngelo on CASP15-cryoEM subset.</p>`,
      key_challenges_zh: `<p><strong>Challenge 1: 计算成本：</strong>需 4×8 H100 + 4-6 周。<strong>Solution:</strong>patch-level masking 降低 75% 内存；混合精度 + activation checkpointing；分阶段冻结-解冻。</p><p><strong>Challenge 2: Non-autoregressive sequence generation instability. Solution:</strong> (a) ESM-2 pretrained token init; (b) iterative refinement; (c) HMM search post-processing.</p><p><strong>Challenge 3: 评估复杂：</strong><strong>Solution:</strong>composite score（CA RMSD + 序列一致性 + completeness + Q-score 相关性）在 CASP15-cryoEM 子集 head-to-head。</p>`,
      evaluation: `<ul><li><strong>Benchmark:</strong> 200 EMDB entries released 2024-2025 (zero-shot), reported across all resolution bands</li><li><strong>Main metrics:</strong> CA RMSD, completeness, sequence identity, TM-score, joint accuracy</li><li><strong>Compare vs:</strong> ModelAngelo, MICA (2025), DeepMainmast, DeepTracer, AlphaFold-3 (sequence-space upper bound)</li><li><strong>Ablation:</strong> per-stage contribution + per-channel supervision</li></ul>`,
      evaluation_zh: `<ul><li><strong>Benchmark:</strong> EMDB 2024-2025 新发布 200 条目（零样本），全分辨率分档</li><li><strong>Main metrics:</strong> CA RMSD, completeness, sequence identity, TM-score, joint accuracy</li><li><strong>Compare vs:</strong> ModelAngelo、MICA (2025)、DeepMainmast、DeepTracer、AlphaFold-3（序列空间上限）</li><li><strong>Ablation:</strong> per-stage contribution + per-channel supervision</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature / Nature Methods</strong>. AlphaFold-3 (Nature 2024) and ModelAngelo (Nature 2024) set the precedent. A unified cryo-EM density foundation model is a Nature main-journal candidate. Backup: Nature Methods.<br><strong>Team:</strong> 1 PI + 2-3 PhDs + 1 engineer. <strong>Timeline:</strong> 12-18 months end-to-end; sub-projects can publish incrementally.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature / Nature Methods</strong>。AlphaFold-3 (Nature 2024)、ModelAngelo (Nature 2024) 是先例。统一冷冻电镜密度基础模型对标 AF-3 在序列空间的地位，是 Nature 主刊候选。备选：Nature Methods。<br><strong>团队：</strong>1 PI + 2-3 博士生 + 1 工程师。<strong>时间线：</strong>端到端 12-18 个月，可能有子项目阶段性发表。</p>`,
      impact: `<strong>If successful:</strong> Becomes structural biology's "AlphaFold for cryo-EM" — fine-tuned for thousands of downstream tasks, cited by every cryo-EM density paper. Estimated 5000+ citations within 3 years.`,
      impact_zh: `<strong>如果成功：</strong>成为结构生物学社区的"冷冻电镜版 AlphaFold" —— 被微调到数千个下游任务，每篇用冷冻电镜密度的论文都引用。3 年内预计 5000+ 引用。`,
      tags: ['★ Flagship', 'Foundation Model', 'Multi-modal', 'SE(3) + Diffusion', '12-18 months']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Methods',
      tier_label_zh: '★★ 子刊 · Nat Methods',
      title_en: "Resolution-Aware Model Builder (1.5–6 Å Universal)",
      title_zh: "分辨率自适应模型构建器（1.5–6 Å 通用）",
      summary_en: "A single neural model that builds atomic models across the full cryo-EM resolution range, conditioned on local resolution and Q-score uncertainty.",
      summary_zh: "单一神经网络模型在全冷冻电镜分辨率范围（1.5–6 Å）下做原子建模，以局部分辨率和 Q-score 为条件。",
      problem: `<p><strong>ModelAngelo (Nature 2024)</strong> was trained on 3,715 pairs filtered to <4 Å. Its performance degrades sharply at 4-6 Å where ~30% of EMDB entries lie. Building separate models per resolution band is impractical. The field needs a single resolution-aware model whose accuracy degrades gracefully with resolution and provides reliable uncertainty.</p>`,
      problem_zh: `<p><strong>ModelAngelo (Nature 2024)</strong> 3,715 对训练数据都筛选了 <4 Å。在 4-6 Å（EMDB 约 30% 条目）性能急剧下降。按分辨率分段训练在数据稀缺下不可行。该领域需要单一分辨率感知模型，精度随分辨率平滑下降并提供可靠不确定性估计。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Plan A is the first dataset with <em>Q-score truth at every backbone atom</em> across resolution-binned Gold/Silver/Bronze tiers. ModelAngelo's training data lacks Q-score (not computed during training). This is what enables the hallucination-aware FiLM modulation.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>Plan A 是首个在分辨率分档（Gold/Silver/Bronze）每个骨架原子都有 <em>Q-score 真值</em>的数据集。ModelAngelo 训练数据缺 Q-score（训练流程中不计算这个量）。这正是幻觉感知 FiLM 调制所需的。`,
      approach: `<p>SE(3)-equivariant 3D U-Net + <strong>resolution-conditional FiLM modulation</strong>: each layer receives a learned embedding of (local resolution, local Q-score) to adjust filters。Plan A full-resolution training with Q-score-weighted loss + curriculum learning (Gold→Silver→Bronze)。</p><p><strong>Key innovation:</strong> Outputs an explicit per-voxel <em>hallucination flag</em>，trained against Q-score — signals uncertainty rather than confidently producing wrong atoms.</p>`,
      approach_zh: `<p>SE(3)-等价 3D U-Net + <strong>分辨率条件 FiLM 调制</strong>: each layer receives (local resolution, local Q-score) embedding and adjusts filters accordingly。Plan A full-resolution training with Q-score-weighted loss + curriculum learning (Gold→Silver→Bronze)。</p><p><strong>关键创新：</strong>输出显式 per-voxel <em>幻觉标志</em>，由 Q-score 监督 —— 模型不确定时告诉你，不是自信地输出错误原子。</p>`,
      key_challenges: `<p><strong>Challenge: 4-6 Å atomic ground truth has inherent errors</strong> (PDB model RMSD 1-2 Å). <strong>Solution:</strong> (a) Q-score weighted loss preventing overfitting to low-quality samples; (b) ChimeraX simulated density as auxiliary supervision;(c) multi-resolution training for resolution-invariant structural features.</p>`,
      key_challenges_zh: `<p><strong>Challenge: 4-6 Å 区间原子真值本身有误差</strong>(PDB model RMSD 1-2 Å)。<strong>Solution:</strong>(a) Q-score 加权 loss；(b) ChimeraX 模拟密度辅助监督；(c) 多分辨率训练让模型学到分辨率不变特征。</p>`,
      evaluation: `<ul><li>Resolution-stratified completeness/RMSD/TM-score at 1.5-2.5/2.5-3.5/3.5-6 Å</li><li>Compare vs: ModelAngelo, DiffModeler, MICA</li><li>Hallucination calibration：predicted confidence vs. actual accuracyreliability diagram</li></ul>`,
      evaluation_zh: `<ul><li>分辨率分档：completeness/RMSD/TM-score 在 1.5-2.5/2.5-3.5/3.5-6 Å</li><li>Compare vs: ModelAngelo, DiffModeler, MICA</li><li>幻觉校准：predicted confidence vs. actual accuracy的可靠性图</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Methods</strong>. DiffModeler (2024), DeepMainmast (2024) both in Nat Methods. This work's breakthrough at 4-6 Å (~30% of EMDB) fills a key gap. <strong>Timeline:</strong> 6-9 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Methods</strong>. DiffModeler (2024), DeepMainmast (2024) both in Nature Methods. This work's breakthrough at 4-6 Å (~30% of EMDB) fills a key gap. <strong>Timeline:</strong> 6-9 months.</p>`,
      impact: `<strong>If successful:</strong> Unlocks ~30% of EMDB entries (4-6 Å) currently unmodellable, enabling atomic-level study of thousands of important biological complexes.`,
      impact_zh: `<strong>如果成功：</strong>解锁 EMDB 中目前无法建模的约 30% 条目（4-6 Å），让数千个重要生物学复合物可做原子级研究。`,
      tags: ['★★ Sub-journal', 'Resolution-Aware', 'Hallucination-Aware', '6-9 months', 'Nat Methods']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Commun',
      tier_label_zh: '★★ 子刊 · Nat Commun',
      title_en: "Sequence-Free Residue Identification (Cryo-EM Metagenomics)",
      title_zh: "无序列氨基酸识别（冷冻电镜宏基因组学）",
      summary_en: "Identify amino acid types directly from cryo-EM density without sequence input — unlocking structural biology for uncharacterized organisms and PTMs.",
      summary_zh: "无需序列输入直接从密度识别氨基酸类型 —— 解锁未表征生物和翻译后修饰蛋白的结构生物学研究。",
      problem: `<p><strong>ModelAngelo (Nature 2024)</strong> identifies novel proteins via HMM search on predicted residue probabilities, but requires sequence databases. For metaproteomics, environmental cryo-EM, and pathogens where sequences are unknown or contaminated, this fails. The community has long sought a "sequence-free" residue typer.</p>`,
      problem_zh: `<p><strong>ModelAngelo (Nature 2024)</strong> 通过 HMM 搜索识别新蛋白，但需要序列数据库。对宏蛋白质组学、环境冷冻电镜、序列未知或污染的病原体样品，此方法失效。社区长期寻求"无序列"残基识别器。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> No public dataset provides large-scale (density_patch ↔ residue_class) supervised pairs. Plan A extracts <strong>~11M training patches</strong> (11K bio-assemblies × ~1000 residues) from label_aa — uniquely the substrate for this task. ModelAngelo's training data has CA positions but not surrounding patches as classification targets.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>没有公开数据集提供大规模（密度块 ↔ 残基类）监督对。Plan A 从 label_aa 提取 <strong>~1100 万训练 patch</strong>（11K 生物组装体 × 每个 ~1000 残基）—— 此任务独家基础。ModelAngelo 训练数据有 CA 位置但不把周围 patch 作为分类目标。`,
      approach: `<p>3D ViT classifier on 8×8×8 Å density patches centered on each CA. 21-way classification (20 standard AAs + 1 unknown). <strong>Key innovations:</strong> (1) Rotation-equivariant augmentation; (2) Q-score-weighted training; (3) Contrastive auxiliary loss pulling same-class patches together; (4) Multi-resolution training with resolution token.</p>`,
      approach_zh: `<p>3D ViT 分类器，输入 8×8×8 Å 密度立方体（CA 为中心）。21 类分类（20 标准氨基酸 + 1 unknown）。<strong>关键创新：</strong>(1) 旋转等价数据增强；(2) Q-score 加权训练；(3) 对比辅助 loss；(4) 多分辨率训练 + resolution token。</p>`,
      key_challenges: `<p><strong>Challenge: Confusable residues (LEU/ILE/VAL, ASP/ASN, GLU/GLN) remain ambiguous below 3 Å and near-random at 4 Å. Solution:</strong>output top-k candidates + Bayesian uncertainty; downstream HMM search handles top-k lists (which is more accurate than top-1 ).</p>`,
      key_challenges_zh: `<p><strong>Challenge: 易混淆残基（LEU/ILE/VAL、ASP/ASN、GLU/GLN）在 < 3 Å 仍混淆，4 Å 近随机：</strong><strong>Solution:</strong>Output top-k candidates + Bayesian uncertainty rather than a single forced prediction. Downstream HMM search handles top-k lists, which is more accurate than top-1 forcing.</p>`,
      evaluation: `<ul><li>Per-class F1 on confusable residue groups (LEU/ILE/VAL, ASP/ASN, etc.)</li><li>Cross-resolution generalization (1.5-3.5 Å)</li><li>Downstream HMM top-1 hit rate improvement</li><li>Metaproteomics sample blind test</li></ul>`,
      evaluation_zh: `<ul><li>Per-class F1 on confusable residue groups (LEU/ILE/VAL, ASP/ASN, etc.)</li><li>Cross-resolution generalization (1.5-3.5 Å)</li><li>Downstream HMM top-1 hit rate improvement</li><li>宏蛋白质组学样品盲测</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Communications</strong>. Clear task scope, <strong>3-4 person-months</strong>. Downstream applications (metaproteomics, PTM detection) appeal to biology readers, fitting Nat Commun's cross-disciplinary profile.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Communications</strong>。任务边界清晰，<strong>3-4 人月</strong>可出成果。下游应用（宏蛋白质组学、PTM 检测）让生物学读者感兴趣。</p>`,
      impact: `<strong>If successful:</strong> Becomes a default plug-in for ModelAngelo / DeepTracer / MICA, deployed in every cryo-EM model-building pipeline worldwide.`,
      impact_zh: `<strong>如果成功：</strong>成为 ModelAngelo / DeepTracer / MICA 的默认插件，部署到全球每个冷冻电镜建模流水线。`,
      tags: ['★★ Sub-journal', '3D ViT', 'Sequence-Free', '3-4 months', 'Nat Commun']
    },
    {
      tier: 'baseline',
      tier_label_en: '★★★ Baseline · Bioinformatics',
      tier_label_zh: '★★★ 稳健保底 · Bioinformatics',
      title_en: "Chain-Aware Backbone Connector for 4-8 Å Maps",
      title_zh: "面向 4-8 Å 密度图的链感知骨架连接器",
      summary_en: "Trace CA backbones with explicit chain assignment from low-resolution cryo-EM density, without requiring a predicted model as prior.",
      summary_zh: "在低分辨率冷冻电镜密度图上追踪 CA 骨架并显式分配链编号，无需预测模型作先验。",
      problem: `<p>Current builders fail at 4-8 Å. DEMO-EM (Nat Comput Sci 2022) and DiffModeler (PMC 2024) require AlphaFold-predicted models as priors — useless when sequence is unknown.</p>`,
      problem_zh: `<p>当前 builder 在 4-8 Å 失败。DEMO-EM (Nat Comput Sci 2022) 和 DiffModeler (PMC 2024) 需要 AlphaFold 预测模型作先验 —— 序列未知或 AF 失败时就废。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Plan A's <code>label_chain</code> + <code>label_segment</code> + <code>label_qscore</code> on Bronze-tier (4-6 Å) entries provides chain-aware ground truth at low resolution — uniquely.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>Plan A 在 Bronze 档（4-6 Å）条目的 <code>label_chain</code> + <code>label_segment</code> + <code>label_qscore</code> 提供低分辨率的链感知真值 —— 独家。`,
      approach: `<p>3D U-Net outputs per-voxel (chain ID, residue index), Transformer head for sequential tracing。Loss: (1) chain consistency (same-chain CA continuity); (2) inter-chain breakpoints。</p>`,
      approach_zh: `<p>3D U-Net 输出每体素（链 ID，残基序号），Transformer head 序列化追踪。Loss: (1) 链一致性；(2) 跨链断点。</p>`,
      key_challenges: `<p><strong>Challenge: 4-8 Å CA positions are inherently imprecise. Solution:</strong> Output multiple candidates + confidence scores; downstream fitting tools (ISOLDE) select the best.</p>`,
      key_challenges_zh: `<p><strong>Challenge: 4-8 Å CA 位置本身不精确：</strong><strong>Solution:</strong>输出多候选 + 置信度，下游 fitting（ISOLDE）选择。</p>`,
      evaluation: `<ul><li>Benchmark: 50 EMDB entries at 4-8 Å</li><li>CA RMSD, chain assignment accuracy, completeness</li><li>Compare vs: DEMO-EM, MICA, DiffModeler at 5+ Å</li></ul>`,
      evaluation_zh: `<ul><li>Benchmark: 50 EMDB entries at 4-8 Å</li><li>CA RMSD, chain assignment accuracy, completeness</li><li>Compare vs: DEMO-EM, MICA, DiffModeler at 5+ Å</li></ul>`,
      publication: `<p>🎯 <strong>Target: Bioinformatics / Cell Reports Methods</strong>. Practical tool, 4-6 person-months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Bioinformatics / Cell Reports Methods</strong>. Practical tool, 4-6 person-months.</p>`,
      impact: `<strong>If successful:</strong> Provides reliable starting model for ~30% of EMDB entries below 4 Å — ribosomes, membrane complexes, large viruses.`,
      impact_zh: `<strong>如果成功：</strong>为 EMDB 中约 30% 低于 4 Å 分辨率的条目提供可靠起始模型 —— 核糖体、膜复合物、大病毒。`,
      tags: ['★★★ Baseline', 'Backbone Tracing', '4-6 months', 'Bioinformatics']
    }
  ],

  // ════════════════════════════════════════════════════════
  // DIRECTION 2: Map Denoising & Resolution Enhancement
  // ════════════════════════════════════════════════════════
  denoising: [
    {
      tier: 'flagship',
      tier_label_en: '★ Flagship · Nat Methods',
      tier_label_zh: '★ 旗舰项目 · Nat Methods',
      title_en: "Universal Cryo-EM Diffusion Restoration",
      title_zh: "通用冷冻电镜扩散修复模型",
      summary_en: "A conditional diffusion model that performs denoising, super-resolution, and anisotropy correction simultaneously — replacing the patchwork of Topaz-Denoise, DeepEMhancer, EMReady with one universal solution.",
      summary_zh: "条件扩散模型同时执行去噪、超分辨率、各向异性校正 —— 用单一通用方案取代 Topaz-Denoise、DeepEMhancer、EMReady 的拼凑。",
      problem: `<p>Cryo-EM post-processing is fragmented: <strong>Topaz-Denoise (Bepler, Nat Commun 2020)</strong> for denoising via N2N; <strong>DeepEMhancer (Comm Biol 2021)</strong> for sharpening; <strong>EMReady2 (bioRxiv 2025)</strong> for general improvement; <strong>DiffModeler (2024)</strong> for backbone tracing. None handle full pipeline. Each needs its own checkpoint and may produce inconsistent outputs when chained.</p>`,
      problem_zh: `<p>冷冻电镜后处理分散：<strong>Topaz-Denoise (Bepler, Nat Commun 2020)</strong> N2N 去噪；<strong>DeepEMhancer (Comm Biol 2021)</strong> 锐化；<strong>EMReady2 (bioRxiv 2025)</strong> 通用改善；<strong>DiffModeler (2024)</strong> 骨架追踪。没有方法处理完整流水线。每工具需自己 checkpoint，串联时可能不一致。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Training a multi-task diffusion model requires paired examples for each task. Plan A is the only dataset with (real, simulated) pairs at 11K scale AND Gold/Silver/Bronze tiers for resolution-aware behavior.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>训练多任务扩散模型需每种任务的配对样本。Plan A 是唯一在 11K 规模提供（真实，模拟）配对 + Gold/Silver/Bronze 分档的数据集。`,
      approach: `<p><strong>Single conditional latent diffusion model:</strong></p><ul><li>3D VAE encoder/decoder for compact latent space</li><li>Diffusion in latent, conditioned on: (a) source map embedding, (b) target resolution, (c) operation token (denoise/sharpen/SR/anisotropy)</li><li>Trained on Plan A's 11K experimental + ChimeraX pairs with multiple task variants per entry (synthetic noise injection, resolution down-sampling, anisotropy simulation)</li></ul><p>Flow Matching variant for fast inference (5-step vs 50-step DDPM).</p>`,
      approach_zh: `<p><strong>单一条件 latent 扩散模型：</strong></p><ul><li>3D VAE encoder/decoder 形成紧凑 latent 空间</li><li>扩散在 latent 空间，条件为：(a) 源图嵌入，(b) 目标分辨率，(c) 操作 token（denoise/sharpen/SR/anisotropy）</li><li>在 Plan A 11K 实验 + ChimeraX 配对上训练，每条目多种任务变体（合成噪声、分辨率降采样、各向异性模拟）</li></ul><p>Flow Matching 变体快速推理（5 步 vs 50 步 DDPM）。</p>`,
      key_challenges: `<p><strong>Challenge 1: ChimeraX simulated maps lack CTF/anisotropy — not a "perfect ground truth". Solution:</strong>Two-stage: Stage 1 uses synthetic data with known CTF deconvolution;Stage 2 real EMDB + ChimeraX targets fine-tune。N2N + supervised mixed loss prevents overfitting.</p><p><strong>Challenge 2: Hallucination risk:</strong>the diffusion model may fabricate details.<strong>Solution:</strong>(a) PHENIX CC validation, not just PSNR；(b) output per-voxel uncertainty map；(c) strictly separate "display" vs "modeling" output modes.</p>`,
      key_challenges_zh: `<p><strong>Challenge 1: ChimeraX 模拟图缺 CTF/各向异性：</strong><strong>Solution:</strong>分两阶段 — Stage 1 合成数据学 CTF 反卷积；Stage 2 真实 EMDB + ChimeraX 目标 fine-tune。N2N + 监督混合 loss。</p><p><strong>Challenge 2: 幻觉风险：</strong><strong>Solution:</strong>(a) PHENIX CC 校验；(b) 输出每体素 uncertainty map；(c) 严格区分"显示用" vs "建模用" mode。</p>`,
      evaluation: `<ul><li>Metrics: FSC improvement, Q-score gain, EMRinger, MapQ, PSNR</li><li>Compare vs: Topaz-Denoise, CryoCARE, DeepEMhancer, EMReady2, CryoTEN, DiffModeler</li><li>Downstream: ModelAngelo accuracy improvement on restored maps</li><li>Hallucination check:sandbox-degraded high-quality map test</li></ul>`,
      evaluation_zh: `<ul><li>Metrics: FSC improvement, Q-score gain, EMRinger, MapQ, PSNR</li><li>Compare vs: Topaz-Denoise, CryoCARE, DeepEMhancer, EMReady2, CryoTEN, DiffModeler</li><li>Downstream: improvement in ModelAngelo accuracy on restored maps</li><li>Hallucination check: hallucination test: verify no new structural features are introduced when applied to sandbox-degraded high-quality maps</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Methods</strong>. Replacing 4 common tools with a unified solution fits Nature Methods' preference for disruptive methodology. DiffModeler 2024 in Nat Methods validates diffusion models. <strong>Timeline:</strong> 9-12 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Methods</strong>. Replacing 4 common tools with a unified solution fits Nature Methods' preference for disruptive methodology. DiffModeler 2024 validates diffusion models in cryo-EM. <strong>Timeline:</strong> 9-12 months.</p>`,
      impact: `<strong>If successful:</strong> Default post-processing tool in every cryo-EM facility, replacing Topaz-Denoise + DeepEMhancer + EMReady combos. Could be integrated into RELION / cryoSPARC.`,
      impact_zh: `<strong>如果成功：</strong>成为每个冷冻电镜设施的默认后处理工具，取代 Topaz-Denoise + DeepEMhancer + EMReady 组合。可能直接集成到 RELION / cryoSPARC。`,
      tags: ['★ Flagship', 'Latent Diffusion', 'Multi-task', 'Flow Matching', '9-12 months', 'Nat Methods']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Commun',
      tier_label_zh: '★★ 子刊 · Nat Commun',
      title_en: "Supervised Cryo-EM Denoising (Beyond Noise2Noise)",
      title_zh: "监督式冷冻电镜去噪（超越 Noise2Noise）",
      summary_en: "Use Plan A's paired experimental + simulated maps as supervised clean targets, complementing the Noise2Noise paradigm that has dominated cryo-EM denoising.",
      summary_zh: "用 Plan A 的实验+模拟配对图作为监督 clean 目标，补充长期主导冷冻电镜去噪的 Noise2Noise 范式。",
      problem: `<p>Topaz-Denoise (Nat Commun 2020), CryoCARE, Warp — all use Noise2Noise because real clean ground truth doesn't exist. The 2025 ScienceDirect labeled dataset has only 650 maps.</p>`,
      problem_zh: `<p>Topaz-Denoise (Nat Commun 2020)、CryoCARE、Warp 都用 Noise2Noise，因真实 clean 真值不存在。2025 ScienceDirect 标注数据集只有 650 图。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Topaz-Denoise explicitly states "we do not require ground truth because none exists". Plan A is the first dataset with 11K (real, synthetic-clean) pairs — directly breaks the 5-year constraint shaping cryo-EM denoising.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>Topaz-Denoise 明确说"不需要真值因为没有"。Plan A 是首个提供 11K (真实, 合成-clean) 配对的数据集 —— 直接打破塑造冷冻电镜去噪研究 5 年的根本约束。`,
      approach: `<p>3D U-Net + perceptual loss (features extracted from Plan A-trained segment/atom classifier). Q-score-weighted losss + structure-aware adversarial loss（output must be recognized by segment/atom the classifier as protein, preventing hallucination）。</p>`,
      approach_zh: `<p>3D U-Net + 感知 loss（从 Plan A 训练好的 segment/atom 分类器提取感知特征）。Q-score-weighted loss + structure-aware adversarial loss (output should be recognized as protein by segment/atom classifier)。</p>`,
      key_challenges: `<p><strong>Challenge: ChimeraX simulation lacks CTF. Solution:</strong> Mixed training: 50% N2N + 50% Plan A supervised. Domain adaptation for smooth simulated→real transfer.</p>`,
      key_challenges_zh: `<p><strong>Challenge: ChimeraX 模拟缺 CTF：</strong><strong>Solution:</strong>混合训练 50% N2N + 50% Plan A 监督。Domain adaptation 让 simulated→real 平滑过渡。</p>`,
      evaluation: `<ul><li>PSNR/SSIM vs ChimeraX simulated</li><li>Q-score improvement, FSC improvement, EMRinger improvement</li><li>Downstream ModelAngelo accuracy</li><li>Hallucination check</li></ul>`,
      evaluation_zh: `<ul><li>PSNR/SSIM vs ChimeraX simulated</li><li>Q-score improvement, FSC improvement, EMRinger improvement</li><li>Downstream ModelAngelo accuracy</li><li>Hallucination check</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Communications</strong>. Topaz-Denoise in Nat Commun; "beyond N2N" is a landmark claim. <strong>Timeline:</strong> 4-6 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Communications</strong>. Topaz-Denoise in Nat Commun; "beyond N2N" is a landmark claim. <strong>Timeline:</strong> 4-6 months.</p>`,
      impact: `<strong>If successful:</strong> "Supervised denoising" alternative to N2N for the entire cryo-EM community. Anticipated 500+ citations in 2 years.`,
      impact_zh: `<strong>如果成功：</strong>为冷冻电镜社区提供 N2N 之外的"监督式去噪"选择。预计 2 年内 500+ 引用。`,
      tags: ['★★ Sub-journal', 'Supervised Denoising', 'Perceptual Loss', '4-6 months', 'Nat Commun']
    },
    {
      tier: 'baseline',
      tier_label_en: '★★★ Baseline · Bioinformatics',
      tier_label_zh: '★★★ 稳健保底 · Bioinformatics',
      title_en: "Q-Score Guided Local Sharpening",
      title_zh: "Q-score 引导的局部锐化",
      summary_en: "Spatially-varying map sharpening driven by per-atom Q-score truth — high-confidence regions get aggressive enhancement; flexible regions remain conservative.",
      summary_zh: "由每原子 Q-score 真值驱动的空间变化锐化 —— 高置信区强力增强，柔性区保守处理。",
      problem: `<p>Standard sharpening (B-factor based) applies uniform sharpening. DeepEMhancer / EMReady2 lack per-residue confidence. Real maps have heterogeneous local quality.</p>`,
      problem_zh: `<p>标准锐化（B 因子）均匀锐化。DeepEMhancer / EMReady2 缺每残基置信度。真实图有异质局部质量。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Plan A is the only dataset shipping per-atom Q-score as ground truth for spatial modulation training.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>Plan A 是唯一提供每原子 Q-score 作为空间调制训练真值的数据集。`,
      approach: `<p>3D U-Net predicts per-voxel sharpening factor, conditioned on input + Q-score. Attention-based smoothing. Trained against ChimeraX targets.</p>`,
      approach_zh: `<p>3D U-Net 预测每体素锐化因子，条件为输入 + Q-score。注意力机制平滑。用 ChimeraX 目标训练。</p>`,
      key_challenges: `<p>Low risk, clear engineering. Main challenge: implement multi-level sharpening modes (low/medium/aggressive) for user task selection.</p>`,
      key_challenges_zh: `<p>Low risk, clear engineering. Main challenge: implement multi-level sharpening modes (low/medium/aggressive) for user task selection.</p>`,
      evaluation: `<ul><li>Local Q-score improvement</li><li>Local EMRinger score</li><li>Blind evaluation by 3 cryo-EM specialists</li></ul>`,
      evaluation_zh: `<ul><li>Local Q-score improvement</li><li>Local EMRinger score</li><li>Blind evaluation by 3 cryo-EM specialists</li></ul>`,
      publication: `<p>🎯 <strong>Target: Bioinformatics / Acta Crystallographica D</strong>. Practical tool, 2-3 person-months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Bioinformatics / Acta Crystallographica D</strong>. Practical tool, 2-3 person-months.</p>`,
      impact: `<strong>If successful:</strong> Default sharpening tool in every cryo-EM lab — dramatically improves manual model building quality.`,
      impact_zh: `<strong>如果成功：</strong>成为每个冷冻电镜实验室默认锐化工具 —— 大幅改善人工建模质量。`,
      tags: ['★★★ Baseline', 'Local Sharpening', '2-3 months', 'Bioinformatics']
    }
  ],

  // ════════════════════════════════════════════════════════
  // DIRECTION 3: Interface & Assembly Prediction
  // ════════════════════════════════════════════════════════
  interface: [
    {
      tier: 'flagship',
      tier_label_en: '★ Flagship · Nat Methods',
      tier_label_zh: '★ 旗舰项目 · Nat Methods',
      title_en: "Cryo-Multimer: Density-Native Interface & Assembly Prediction",
      title_zh: "Cryo-Multimer：密度原生的界面与组装体预测",
      summary_en: "Predict protein-protein interfaces, chain assignments, and oligomeric state directly from cryo-EM density — no atomic model, no sequence required. The cryo-EM analog of AlphaFold-Multimer.",
      summary_zh: "直接从冷冻电镜密度预测蛋白-蛋白界面、链分配和寡聚态 —— 不需原子模型、不需序列。冷冻电镜版的 AlphaFold-Multimer。",
      problem: `<p><strong>AlphaFold-Multimer (Evans et al., 2022)</strong> achieves 60% dimer accuracy, only 23-34% on hard heteromeric targets. Critically requires sequence inputs, failing on metaproteomics or PTMs. <strong>MaSIF (Nat Methods 2020)</strong>, <strong>PInet</strong>, <strong>EquiDock</strong> all require atomic coordinates. For cryo-EM, this means waiting months until atomic modeling completes before interface analysis can begin.</p>`,
      problem_zh: `<p><strong>AlphaFold-Multimer (Evans 等, 2022)</strong> 二聚体精度 60%，难异源仅 23-34%。需序列输入，宏蛋白质组学或 PTM 失效。<strong>MaSIF (Nat Methods 2020)</strong>、<strong>PInet</strong>、<strong>EquiDock</strong> 全要原子坐标。对冷冻电镜，这意味着等待原子建模完成数月后才能开始界面分析。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Plan A's <code>label_interface</code> + <code>label_chain</code> on 11K bio-assemblies is uniquely the substrate. AlphaFold-Multimer training used PDB complexes (no density). No dataset has (density_voxel, interface_label, chain_id) triple at scale.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>Plan A 在 11K 生物组装体的 <code>label_interface</code> + <code>label_chain</code> 是独家。AlphaFold-Multimer 训练用 PDB 复合物（无密度）。没有数据集大规模提供（密度体素，界面标签，链 ID）三元组。`,
      approach: `<p><strong>3D U-Net + Cross-Chain Attention Transformer:</strong></p><ul><li>U-Net outputs per-voxel (chain ID, interface probability, oligomeric state class)</li><li>Cross-chain attention captures long-range inter-chain dependencies</li><li>multi-task:label_interface + label_chain + label_segment three-task mutual regularization</li></ul>`,
      approach_zh: `<p><strong>3D U-Net + 跨链注意力 Transformer：</strong></p><ul><li>U-Net 输出每体素（链 ID, 界面概率, 寡聚态）</li><li>cross-chain attention captures long-range dependencies</li><li>multi-task: multi-task joint training of label_interface + label_chain + label_segment (they mutually regularize each other)</li></ul>`,
      key_challenges: `<p><strong>Challenge: Interface residues indistinct at low resolution (CA blurred CAs):</strong><strong>Solution:</strong>(a) multi-task regularization (chain + interface mutually constrain each other);(b) Q-score weighted loss；(c) Primary results focus on <4 Å，5+ Å demonstrate graceful degradation。</p>`,
      key_challenges_zh: `<p><strong>Challenge: 低分辨率界面残基难区分（CA 模糊）：</strong><strong>Solution:</strong>(a) 多任务正则化；(b) Q-score 加权 loss；(c) 主结果聚焦 <4 Å，5+ Å 展示优雅降级。</p>`,
      evaluation: `<ul><li>Voxel-level:interface AUC, F1, IoU</li><li>Residue-level (aggregated to CA, per-residue interface F1</li><li>Compare vs: (a) interface extracted from AFM-fitted models; (b) simple distance threshold</li><li>Downstream: use predicted interface to guide ModelAngelo</li></ul>`,
      evaluation_zh: `<ul><li>Voxel-level: interface AUC, F1, IoU</li><li>Residue-level: aggregated to CA, per-residue F1</li><li>对比：(a) AFM 输出的界面；(b) 简单距离阈值</li><li>Downstream: use predicted interface to guide ModelAngelo</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Methods</strong>. MaSIF (Nat Methods 2020) established "sequence→interface". Cryo-Multimer's "density→interface" is equivalent scope. <strong>Timeline:</strong> 6-9 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Methods</strong>. MaSIF (Nat Methods 2020) established "sequence→interface". Cryo-Multimer's "density→interface" is equivalent scope. <strong>Timeline:</strong> 6-9 months.</p>`,
      impact: `<strong>If successful:</strong> Cryo-EM specialists can extract interaction information within days of data collection instead of months after modeling — fundamentally changing the workflow. Especially impactful for drug discovery (allosteric site identification).`,
      impact_zh: `<strong>如果成功：</strong>冷冻电镜专家能在数据采集后数天提取相互作用信息，而非建模后数月 —— 根本改变工作流。对药物发现（变构位点识别）尤其有影响。`,
      tags: ['★ Flagship', 'Multi-task', 'Cross-Chain Attention', '6-9 months', 'Nat Methods']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Commun',
      tier_label_zh: '★★ 子刊 · Nat Commun',
      title_en: "Cryo-MaSIF: Density-Native Surface Fingerprinting",
      title_zh: "Cryo-MaSIF：密度原生的表面指纹",
      summary_en: "A 'MaSIF for cryo-EM' — learn density-based molecular surface fingerprints for protein interaction prediction and binding site identification.",
      summary_zh: "'冷冻电镜版 MaSIF' —— 学习基于密度的分子表面指纹，用于蛋白相互作用预测和结合位点识别。",
      problem: `<p><strong>MaSIF (Gainza et al., Nat Methods 2020)</strong> learns molecular surface fingerprints from atomic models via geometric deep learning. Cannot operate on cryo-EM density. For drug discovery, density-level surface descriptors would enable binder identification before atomic modeling.</p>`,
      problem_zh: `<p><strong>MaSIF (Gainza 等, Nat Methods 2020)</strong> 通过几何深度学习从原子模型学习分子表面指纹，无法在冷冻电镜密度上工作。对药物发现，密度级表面描述符能在原子建模前识别 binder。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Need (surface, interface_label, aa_chemistry) triple — only Plan A provides label_segment + label_interface + label_aa simultaneously on 11K entries.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>需要（表面、界面标签、氨基酸化学）三元组 —— 只有 Plan A 在 11K 条目同时提供 label_segment + label_interface + label_aa。`,
      approach: `<p>extract protein surface from label_segment; learn fingerprint on each patch (PointNet++/3D Transformer)；label_interface contrastive learning (interface patch should have complementary fingerprints);label_aa + label_qscore auxiliary supervision。</p>`,
      approach_zh: `<p>extract protein surface from label_segment; learn fingerprint on each patch (PointNet++/3D Transformer)；label_interface contrastive learning (complementary fingerprints for interface patches)；label_aa + label_qscore auxiliary supervision。</p>`,
      key_challenges: `<p><strong>Challenge: Surface extraction is unstable at low resolution. Solution:</strong> Use Gold-tier entries as primary training set.</p>`,
      key_challenges_zh: `<p><strong>Challenge: Surface extraction is unstable at low resolution. Solution:</strong> Use Gold-tier entries as primary training set.</p>`,
      evaluation: `<ul><li>Compare vs. MaSIF (theoretical upper bound)</li><li>Drug-chemistry blind test on candidate binding sites in EMDB</li><li>Downstream binder ranking AUC</li></ul>`,
      evaluation_zh: `<ul><li>Compare vs. MaSIF (theoretical upper bound)</li><li>Drug-chemistry blind test on candidate binding sites in EMDB</li><li>Downstream binder ranking AUC</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Communications</strong>. MaSIF in Nat Methods, density version fits Nat Commun. <strong>Timeline:</strong> 6-9 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Communications</strong>. MaSIF in Nat Methods, density version fits Nat Commun. <strong>Timeline:</strong> 6-9 months.</p>`,
      impact: `<strong>If successful:</strong> Enables fragment-based drug discovery directly from cryo-EM density, accelerating drug pipelines by months.`,
      impact_zh: `<strong>如果成功：</strong>让基于片段的药物发现直接从冷冻电镜密度启动，加速药物流程数月。`,
      tags: ['★★ Sub-journal', 'Surface Learning', 'Contrastive', '6-9 months', 'Nat Commun']
    },
    {
      tier: 'baseline',
      tier_label_en: '★★★ Baseline · Bioinformatics',
      tier_label_zh: '★★★ 稳健保底 · Bioinformatics',
      title_en: "Oligomeric State Classifier from Mid-Resolution Density",
      title_zh: "中等分辨率密度的寡聚态分类器",
      summary_en: "Predict oligomeric state (monomer/dimer/trimer/...) directly from cryo-EM density at 4-8 Å, useful in early-stage data analysis before atomic modeling.",
      summary_zh: "直接从 4-8 Å 冷冻电镜密度预测寡聚态 —— 原子建模前的早期数据分析。",
      problem: `<p>Currently manual judgment by specialists. PISA (Krissinel 2007) needs atomic models. EMDB symmetry annotation added only after modeling. New data has unknown oligomeric state for weeks-months.</p>`,
      problem_zh: `<p>目前靠专家人工判断。PISA (Krissinel 2007) 需原子模型。EMDB 对称注释只在建模后添加。新数据的寡聚态数周-数月未知。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Only dataset with chain count labels on bio-assembly-expanded structures at 11K scale.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>唯一在 11K 规模生物组装体展开结构上标注链数的数据集。`,
      approach: `<p>3D CNN (ResNet-3D) + global pooling + classification head (1-24+ classes including "irregular/no-symmetry"). Multi-task: simultaneously predict point group symmetry (C2, D3, T, O, I)。</p>`,
      approach_zh: `<p>3D CNN (ResNet-3D) + global pooling + classification head (1-24+ classes including "irregular/no-symmetry")。Multi-task: simultaneously predict point group symmetry (C2, D3, T, O, I)。</p>`,
      key_challenges: `<p><strong>Challenge: Class imbalance (many dimers, few T/I symmetry entries). Solution:</strong> Class-balanced sampling + focal loss.</p>`,
      key_challenges_zh: `<p><strong>Challenge: 类别不均衡：</strong><strong>Solution:</strong>类别平衡采样 + focal loss。</p>`,
      evaluation: `<ul><li>Top-1 / Top-3 accuracy</li><li>Resolution robustness at 4/5/6/8 Å</li><li>Compare vs: PISA (theoretical upper bound), cryoSPARC Symmetry Search</li><li>Inference < 5s/sample</li></ul>`,
      evaluation_zh: `<ul><li>Top-1 / Top-3 accuracy</li><li>Resolution robustness at 4/5/6/8 Å</li><li>Compare vs: PISA (theoretical upper bound), cryoSPARC Symmetry Search</li><li>Inference < 5s/sample</li></ul>`,
      publication: `<p>🎯 <strong>Target: JCIM / Bioinformatics</strong>. Practical tool, 2-3 person-months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：JCIM / Bioinformatics</strong>. Practical tool, 2-3 person-months.</p>`,
      impact: `<strong>If successful:</strong> Integrated into EMDB submission to auto-populate symmetry metadata.`,
      impact_zh: `<strong>如果成功：</strong>集成到 EMDB 提交流程自动填充对称元数据。`,
      tags: ['★★★ Baseline', 'Classification', '2-3 months', 'Bioinformatics']
    }
  ],

  // ════════════════════════════════════════════════════════
  // DIRECTION 4: Density-Based Domain & Fold Discovery
  // ════════════════════════════════════════════════════════
  domain_fold: [
    {
      tier: 'flagship',
      tier_label_en: '★ Flagship · Nat Biotechnol / Nat Methods',
      tier_label_zh: '★ 旗舰项目 · Nat Biotechnol / Nat Methods',
      title_en: "Cryo-Foldseek: Density-Based Structural Search at EMDB Scale",
      title_zh: "Cryo-Foldseek：EMDB 规模的密度结构搜索",
      summary_en: "A 'Foldseek for cryo-EM' — search EMDB by density similarity at millisecond latency, without atomic models. Discover novel folds, convergent evolution, and structural mimics directly from density.",
      summary_zh: "'冷冻电镜版 Foldseek' —— 毫秒级延迟按密度相似度搜索 EMDB，无需原子模型。直接从密度发现新折叠、趋同进化、结构模仿。",
      problem: `<p><strong>Foldseek (van Kempen et al., Nat Biotechnol 2024)</strong> revolutionized structural homology search via 3Di alphabet — but requires atomic structures. <strong>Foldseek-Multimer (Nat Methods 2025)</strong> still atomic. <strong>Foldclass/Merizo-search (Bioinform Adv 2025)</strong> deep-learning alternative — still atomic. For the ~38% of EMDB entries without atomic models, no structural search is possible.</p>`,
      problem_zh: `<p><strong>Foldseek (van Kempen 等, Nat Biotechnol 2024)</strong> 用 3Di 字母表革命性加速结构同源搜索 —— 需原子结构。<strong>Foldseek-Multimer (Nat Methods 2025)</strong> 仍需原子。<strong>Foldclass/Merizo-search (Bioinform Adv 2025)</strong> 深度学习替代，仍需原子。对 EMDB 约 38% 缺原子模型的条目，无法做结构搜索。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Need (density, domain_partition, multi-resolution variants) triple. Plan A is the only dataset with Merizo-derived label_domain on 11K bio-assemblies + tier-graded metadata + paired ChimeraX simulated maps for data augmentation.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>需要（密度、域划分、多分辨率变体）三元组。Plan A 是唯一在 11K 生物组装体上有 Merizo 衍生 label_domain + 分档元数据 + 配对 ChimeraX 模拟图用于数据增强的数据集。`,
      approach: `<p><strong>Density Encoder + Contrastive Learning:</strong></p><ul><li>3D Transformer maps density to 256-d embedding</li><li>Domain-level encoding via label_domain: each domain independent embedding (matching Merizo-search)</li><li>Positive pairs: same protein different EMDB entries OR simulated noise variants OR CATH-homologous entries</li><li>FAISS-indexed 55K embeddings → millisecond search</li></ul><p><strong>Cross-space alignment:</strong> map density vectors into Foldseek's 3Di space via learned projection — enables cross-modal search.</p>`,
      approach_zh: `<p><strong>密度编码器 + 对比学习：</strong></p><ul><li>3D Transformer 把密度映射到 256 维 embedding</li><li>Domain-level encoding (via label_domain): each domain gets independent embedding (matching Merizo-search)</li><li>Positive pairs: same protein different EMDB entries OR simulated noise variants OR CATH-homologous entries</li><li>FAISS-indexed 55K embeddings → millisecond-latency search</li></ul><p><strong>跨空间对齐：</strong>把密度向量映射到 Foldseek 3Di 空间 —— 支持跨模态搜索。</p>`,
      key_challenges: `<p><strong>Challenge: EMDB has few "same-protein, multiple-entry" pairs for contrastive training:</strong><strong>Solution:</strong>(a) Data augmentation：resolution downsampling, noise injection, rotation;(b)  ChimeraX simulated maps as positive pair；(c) use PDB known CATH homologs as positive。</p>`,
      key_challenges_zh: `<p><strong>Challenge: EMDB"同蛋白多条目"不多：</strong><strong>Solution:</strong>(a) 数据增强；(b) 用 ChimeraX 模拟图作 positive；(c) 借用 PDB 已知 CATH 同源作 positive。</p>`,
      evaluation: `<ul><li>CATH consistency: CATH homology rate of top-k results (Foldseek-style)</li><li>Cross-resolution robustness</li><li>Speed: 1M queries/min</li><li>Compare vs: traditional real-space CC, FSC</li><li>Novel discoveries: previously unrecognized homologs in EMDB (biologically validated)</li></ul>`,
      evaluation_zh: `<ul><li>CATH consistency: CATH homology rate of top-k results</li><li>Cross-resolution robustness</li><li>Speed: 1M queries/min</li><li>Compare vs: traditional real-space CC, FSC</li><li>Novel discoveries: previously unrecognized homologs in EMDB (biologically validated)</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Biotechnology / Nature Methods</strong>。Foldseek in Nat Biotechnol; Foldseek-Multimer in Nat Methods 2025. "Foldseek for cryo-EM"is a community killer-app, potentially becoming EMDB the official search engine.<strong>Timeline:</strong>6-9 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Biotechnology / Nature Methods</strong>. Foldseek in Nat Biotechnol; Foldseek-Multimer in Nat Methods 2025. "Foldseek for cryo-EM" is a killer tool, potential EMDB official search engine. <strong>Timeline:</strong> 6-9 months.</p>`,
      impact: `<strong>If successful:</strong> The "reverse image search" for cryo-EM — drop in any density, find similar entries instantly. Accelerates discovery of novel folds, convergent evolution, pathogen mimics. 1000+ citations within 2 years.`,
      impact_zh: `<strong>如果成功：</strong>成为冷冻电镜的"以图搜图" —— 输入任意密度立即找到相似条目。加速新折叠、趋同进化、病原体模仿的发现。2 年内 1000+ 引用。`,
      tags: ['★ Flagship', 'Contrastive Learning', 'Density Search', '6-9 months', 'Nat Biotechnol']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Commun',
      tier_label_zh: '★★ 子刊 · Nat Commun',
      title_en: "Density-Native Domain Segmentation (Cryo-Merizo)",
      title_zh: "密度原生的结构域分割（Cryo-Merizo）",
      summary_en: "Segment structural domains directly from cryo-EM density, replacing Merizo's dependence on atomic models.",
      summary_zh: "直接从冷冻电镜密度分割结构域，替代 Merizo 对原子模型的依赖。",
      problem: `<p>Merizo (Nat Commun 2023), SWORD, UniDoc, DPAM — all require atomic coordinates. For ~38% of EMDB entries without atomic models, domain analysis is impossible.</p>`,
      problem_zh: `<p>Merizo (Nat Commun 2023)、SWORD、UniDoc、DPAM 全要原子坐标。对约 38% 无原子模型的 EMDB 条目，domain 分析不可能。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Need (density_voxel, domain_id, chain_id) triple. Plan A is the first to apply Merizo on 11K atomic models AND propagate domain labels to corresponding density voxels — uniquely.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>需要（密度体素，domain ID，链 ID）三元组。Plan A 是首个把 Merizo 应用到 11K 原子模型并把 domain 标签传播到对应密度体素的 —— 独家。`,
      approach: `<p>3D U-Net + instance segmentation head (Mask R-CNN-3D style), outputting per-voxel domain ID。Boundary-aware weighting：domain boundaries correspond to linker regions — upweighted in boundary loss。</p>`,
      approach_zh: `<p>3D U-Net + instance segmentation head (Mask R-CNN-3D style), outputting per-voxel domain ID。Boundary-aware weighting：domain boundaries correspond to linker regions — upweighted in boundary loss。</p>`,
      key_challenges: `<p><strong>Challenge: Merizo itself makes errors on low-resolution atomic models (noisy labels). Solution:</strong> Use Gold/Silver tier as high-confidence training set; Bronze tier for evaluation only; Q-score weighting filters low-quality domain labels.</p>`,
      key_challenges_zh: `<p><strong>Challenge: Merizo 在低分辨率原子模型上有错：</strong><strong>Solution:</strong>用 Gold/Silver 档作高置信训练集；Bronze 档作 evaluation；Q-score 加权过滤。</p>`,
      evaluation: `<ul><li>Merizo consistency: IoU when atomic model is available</li><li>Without atomic model: expert blind evaluation of 30 entries at 4-6 Å</li><li>Downstream: predicted domains guide DEMO-EM-style multi-domain assembly</li></ul>`,
      evaluation_zh: `<ul><li>Merizo consistency: IoU when atomic model is available</li><li>Without atomic model: expert blind evaluation of 30 entries at 4-6 Å</li><li>Downstream: predicted domains guide DEMO-EM-style multi-domain assembly</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Communications</strong>. Merizo in Nat Commun 2023; density-native domain segmentation is its density-space extension. <strong>Timeline:</strong> 4-6 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Communications</strong>. Merizo in Nat Commun 2023; density-native domain segmentation is its density-space extension. <strong>Timeline:</strong> 4-6 months.</p>`,
      impact: `<strong>If successful:</strong> Enables domain-level analysis of ~40% of EMDB entries without atomic models.`,
      impact_zh: `<strong>如果成功：</strong>让 EMDB 中约 40% 无原子模型的条目可做 domain 级分析。`,
      tags: ['★★ Sub-journal', 'Instance Segmentation', '4-6 months', 'Nat Commun']
    },
    {
      tier: 'baseline',
      tier_label_en: '★★★ Baseline · Bioinformatics',
      tier_label_zh: '★★★ 稳健保底 · Bioinformatics',
      title_en: "End-to-End Density-to-Secondary-Structure",
      title_zh: "端到端密度到二级结构预测",
      summary_en: "Predict per-residue secondary structure (Helix/Strand/Coil) directly from cryo-EM density without model building.",
      summary_zh: "无需建模从密度预测每残基二级结构（α-螺旋/β-折叠/无规则卷曲）。",
      problem: `<p>SS prediction from sequence (NetSurfP, ESM-2) is mature but doesn't use cryo-EM. Cryo-EM SS analysis requires atomic models. For mid-resolution data, even SS-level info would be valuable.</p>`,
      problem_zh: `<p>从序列预测 SS（NetSurfP、ESM-2）成熟但不用冷冻电镜。冷冻电镜 SS 分析需原子模型。对中等分辨率，SS 级信息也有价值。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Plan A's <code>label_ss</code> at every CA voxel × 11K entries is uniquely the substrate.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>Plan A 在每个 CA 体素 × 11K 条目的 <code>label_ss</code> 是独家基础。`,
      approach: `<p>3D U-Net + auxiliary heads。label_ss (CA-only, 3 classes) as primary supervision。label_segment for region weighting。Topology consistency loss：contiguous helix contiguous H predictions.</p>`,
      approach_zh: `<p>3D U-Net + 辅助头。label_ss (CA-only, 3 classes) as primary supervision。label_segment for region weighting。topology consistency loss: contiguous helices should have contiguous H predictions。</p>`,
      key_challenges: `<p>Low risk. Main challenge: α/β discrimination is difficult above 6 Å resolution.</p>`,
      key_challenges_zh: `<p>Low risk. Main challenge: α/β discrimination is difficult above 6 Å resolution.</p>`,
      evaluation: `<ul><li>Per-voxel SS accuracy</li><li>Per-residue SS accuracy (vs. DSSP)</li><li>Multi-resolution boundary at 2/3/4/6 Å</li></ul>`,
      evaluation_zh: `<ul><li>Per-voxel SS accuracy</li><li>Per-residue SS accuracy (vs. DSSP)</li><li>Multi-resolution boundary at 2/3/4/6 Å</li></ul>`,
      publication: `<p>🎯 <strong>Target: Bioinformatics</strong>. Foundational module, 2-3 person-months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Bioinformatics</strong>. Foundational module, 2-3 person-months.</p>`,
      impact: `<strong>If successful:</strong> Instant SS topology before atomic modeling — guides experimental design.`,
      impact_zh: `<strong>如果成功：</strong>原子建模前瞬时 SS 拓扑 —— 指导实验设计。`,
      tags: ['★★★ Baseline', 'SS Prediction', '2-3 months', 'Bioinformatics']
    }
  ],

  // ════════════════════════════════════════════════════════
  // DIRECTION 5: Cryo-EM Foundation Model & QC
  // ════════════════════════════════════════════════════════
  foundation: [
    {
      tier: 'flagship',
      tier_label_en: '★ Flagship · Nature / Nat Methods',
      tier_label_zh: '★ 旗舰项目 · Nature / Nat Methods',
      title_en: "CryoFM-3D: The First 3D Cryo-EM Vision Foundation Model",
      title_zh: "CryoFM-3D：首个 3D 冷冻电镜视觉基础模型",
      summary_en: "A self-supervised 3D foundation model on cryo-EM density volumes — a single pretrained backbone powering all downstream tasks via fine-tuning. The cryo-EM analog of SAM (Segment Anything).",
      summary_zh: "冷冻电镜密度体素上的自监督 3D 基础模型 —— 单一预训练主干通过微调驱动所有下游任务。冷冻电镜版的 SAM。",
      problem: `<p>Cryo-EM foundation model landscape is fragmented: <strong>Cryo-IEF (Nat Methods 2025)</strong>: 65M particles, 2D only. <strong>DRACO (2024)</strong>: 270K micrographs, MAE+N2N, 2D only. <strong>CryoFM (Zhou 2024)</strong>: 3D flow-based but only synthetic curated maps. <strong>CryoCRAB (Sci Data 2025)</strong>: 746 proteins, 2D only. None is a real 3D foundation model on EMDB density with multi-channel annotations.</p>`,
      problem_zh: `<p>冷冻电镜基础模型分散：<strong>Cryo-IEF (Nat Methods 2025)</strong>：6500 万粒子，仅 2D。<strong>DRACO (2024)</strong>：27 万显微图，MAE+N2N，仅 2D。<strong>CryoFM (Zhou 2024)</strong>：3D 流模型但只在合成 curated 图。<strong>CryoCRAB (Sci Data 2025)</strong>：746 蛋白，仅 2D。没有真正在 EMDB 3D 密度 + 多通道标注上的 3D 基础模型。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> No other dataset has 3D EMDB density + multi-channel structural annotation at scale. Cryo-IEF 2D, CryoFM synthetic-only, CryoCRAB 2D. Plan A is the unique substrate for a real 3D cryo-EM foundation model.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>没有其他数据集大规模提供 3D EMDB 密度 + 多通道结构标注。Cryo-IEF 2D，CryoFM 仅合成，CryoCRAB 2D。Plan A 是真正 3D 冷冻电镜基础模型的独家基础。`,
      approach: `<p><strong>Two-stage training:</strong></p><ul><li><strong>Stage 1 — 3D MAE pretraining:</strong> 3D Swin Transformer + patch-level masking (50%). 11K Plan A volumes + augmentation (rotation, noise, resolution down-sampling → effective 200K+).</li><li><strong>Stage 2 — Multi-task fine-tuning:</strong> 9 task heads (8 channels + simulated density), joint training on Plan A.</li></ul><p><strong>Multimodal contrastive head:</strong> Add encoders for (sequence, atomic model, QC metrics) with CLIP-style contrastive loss.</p>`,
      approach_zh: `<p><strong>两阶段训练：</strong></p><ul><li><strong>阶段 1 — 3D MAE 预训练：</strong>3D Swin Transformer + patch-level masking (50%)。11K Plan A 体素 + 增强（旋转、噪声、分辨率降采样 → 等效 20 万+）。</li><li><strong>阶段 2 — 多任务微调：</strong>9 个任务头（8 通道 + 模拟密度），在 Plan A 上联合训练。</li></ul><p><strong>多模态对比头：</strong>添加（序列、原子模型、QC 指标）encoder，CLIP 风格对比 loss。</p>`,
      key_challenges: `<p><strong>Challenge 1: 11K entries is small for a foundation model (compare: Cryo-IEF used 65M). Solution:</strong>(a) data augmentation achieves ×20; (b) Plan A 8-channel supervision provides 8× signal per sample;(c) expand with PDB + ChimeraX synthetic density for pretraining.</p><p><strong>Challenge 2: Training cost:</strong>8-16 × H100 + 4-8 weeks.<strong>Solution:</strong>staged training (2D backbone first, then 3D); mixed precision; distributed data parallelism.</p>`,
      key_challenges_zh: `<p><strong>Challenge 1: 11K 对基础模型偏少：</strong><strong>Solution:</strong>(a) 数据增强让有效规模 ×20；(b) 多通道监督让每样本提供 8 倍信号；(c) 引入 PDB + ChimeraX 合成密度扩展。</p><p><strong>Challenge 2: 训练成本：</strong><strong>Solution:</strong>分阶段（先 2D，再 3D）；混合精度；分布式数据并行。</p>`,
      evaluation: `<ul><li>Pretraining: MAE reconstruction loss, embedding visualization (t-SNE)</li><li>Multi-task: joint 8-channel F1</li><li>Downstream transfer:few-shot on cryo-EM small benchmarks (EM Model Challenge, CryoBench)</li><li>entriesSOTA for each downstream task</li></ul>`,
      evaluation_zh: `<ul><li>Pretraining: MAE reconstruction loss + t-SNE embedding visualization</li><li>Multi-task fine-tuning: joint 8-channel F1 score</li><li>Downstream transfer: few-shot performance on cryo-EM benchmarks (EM Model Challenge, CryoBench)</li><li>Compare vs: SOTA for each downstream task</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature / Nature Methods / NeurIPS</strong>。The first real 3D cryo-EM foundation model — a milestone comparable to Cryo-IEF (Nat Methods 2025) but 3D scope.<strong>Team:</strong>1 PI + 3-4 PhD students + 1 engineer.<strong>Timeline:</strong>12-18 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature / Nature Methods / NeurIPS</strong>. First real 3D cryo-EM foundation model; comparable to Cryo-IEF (Nat Methods 2025) but 3D. <strong>Team:</strong> 1 PI + 3-4 PhDs + 1 engineer. <strong>Timeline:</strong> 12-18 months.</p>`,
      impact: `<strong>If successful:</strong> The cryo-EM equivalent of SAM — a single pretrained model powering all downstream tasks via few-shot fine-tuning. The most strategically important paper for structural biology AI this decade.`,
      impact_zh: `<strong>如果成功：</strong>冷冻电镜版的 SAM —— 单一预训练模型通过 few-shot 微调驱动所有下游任务。本十年结构生物学 AI 社区战略意义最强的论文。`,
      tags: ['★ Flagship', 'Foundation Model', '3D MAE', 'Multimodal', '12-18 months', 'Nature']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Methods',
      tier_label_zh: '★★ 子刊 · Nat Methods',
      title_en: "Unified AI Validator for wwPDB Cryo-EM Depositions",
      title_zh: "wwPDB 冷冻电镜沉积的统一 AI 验证器",
      summary_en: "A single AI model subsuming Q-score, EMRinger, PHENIX CC into unified per-voxel + per-residue + global quality scores with uncertainty quantification.",
      summary_zh: "单一 AI 模型将 Q-score、EMRinger、PHENIX CC 整合为每体素+每残基+全局质量分数，含不确定性量化。",
      problem: `<p>wwPDB requires Q-score (since Sept 2023) plus EMRinger, PHENIX Map-Model FSC, EMDB Atom Inclusion. Current AI methods: <strong>DeepQs</strong> trained on 496 pairs only; <strong>DAQ-score</strong> uses CNN without large-scale QC truth. Different tools sometimes disagree.</p>`,
      problem_zh: `<p>wwPDB 要求 Q-score (2023.9 起) 加 EMRinger、PHENIX Map-Model FSC、EMDB Atom Inclusion。当前 AI：<strong>DeepQs</strong> 仅 496 对训练；<strong>DAQ-score</strong> 用 CNN 但缺大规模 QC 真值。不同工具有时不一致。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> DeepQs has only 496 pairs. Plan A is 22× larger AND ships PHENIX-computed multi-metric ground truth — the exact substrate for training a unified validator.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>DeepQs 仅 496 对。Plan A 是 22 倍大，附带 PHENIX 计算的多指标真值 —— 训练统一验证器的精确基础。`,
      approach: `<p>Trained on Plan A 11K entries + full PHENIX QC ground truth:Head 1 per-voxel quality [0,1]；Head 2 per-residue + uncertainty interval；Head 3 global quality summary；Head 4 error detection (chain misassignment, sequence mismatch)。Architecture: 3D ViT + ConvNeXt hybrid。</p>`,
      approach_zh: `<p>Trained on Plan A 11K entries + full PHENIX QC ground truth:Head 1: per-voxel quality [0,1]; Head 2: per-residue + uncertainty interval; Head 3: global quality summary; Head 4: error detection。Architecture: 3D ViT + ConvNeXt hybrid。</p>`,
      key_challenges: `<p><strong>Challenge: PHENIX Q-score itself contains noise. Solution:</strong> Use Gold-tier entries as high-confidence training subset; cross-calibrate with multiple QC metrics; output confidence intervals so users can judge reliability.</p>`,
      key_challenges_zh: `<p><strong>Challenge: PHENIX Q-score itself has noise. Solution:</strong> Use Gold-tier entries as high-confidence training subset; multi-metric cross-calibration; output confidence intervals so users know when not to trust the prediction.</p>`,
      evaluation: `<ul><li>Correlation with PHENIX ground truth</li><li>Consistency with EMRinger / Q-score</li><li>Error detection: synthetic chain misassignment injection</li><li>Compare vs: DeepQs, DAQ-score</li></ul>`,
      evaluation_zh: `<ul><li>Correlation with PHENIX ground truth</li><li>Consistency with EMRinger / Q-score</li><li>Error detection: synthetic chain misassignment injection</li><li>Compare vs: DeepQs, DAQ-score</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Methods</strong>. 22× larger than DeepQs + multi-task + uncertainty quantification. Likely integrated into wwPDB. <strong>Timeline:</strong> 6-9 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Methods</strong>. 22× larger than DeepQs + multi-task + uncertainty quantification. Likely integrated into wwPDB. <strong>Timeline:</strong> 6-9 months.</p>`,
      impact: `<strong>If successful:</strong> Integrated into wwPDB validation as official AI validator. Every PDB deposition worldwide goes through this model — most-deployed AI in structural biology.`,
      impact_zh: `<strong>如果成功：</strong>集成进 wwPDB 验证作为官方 AI 验证器。全球每个 PDB 沉积都经过这个模型 —— 结构生物学部署最广的 AI。`,
      tags: ['★★ Sub-journal', 'AI Validator', 'Multi-task', '6-9 months', 'Nat Methods']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · Nat Commun',
      tier_label_zh: '★★ 子刊 · Nat Commun',
      title_en: "Automated wwPDB Model Error Detection",
      title_zh: "自动化 wwPDB 模型错误检测",
      summary_en: "Detect chain misassignment, wrong residue types, and systematic errors in deposited PDB models by comparing against cryo-EM density.",
      summary_zh: "通过对照冷冻电镜密度图，检测已沉积 PDB 模型中的链错配、错误残基类型、系统性错误。",
      problem: `<p>wwPDB validation flags geometry issues but can't detect model-density mismatches beyond global metrics. Among existing PDB models there are known cases of chain misassignment, residue misidentification. Manual detection requires hours of expert review per structure.</p>`,
      problem_zh: `<p>wwPDB 验证标记几何问题但无法检测模型-密度不匹配（除全局指标）。已有 PDB 模型中存在已知链错配、残基误识别。人工检测每结构需数小时专家审核。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> Need (density, model, ground truth label_chain + label_aa + label_qscore) on 11K entries. Only Plan A has this triplet at scale.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>需要 (密度, 模型, 真值 label_chain + label_aa + label_qscore) 在 11K 条目。只有 Plan A 大规模提供。`,
      approach: `<p>Train error detector on Plan A 11K (density, model, labels): (1) Inject synthetic errors (chain ID swaps, residue mutations, coordinate shifts); (3) model learns real vs error-injected models;(4) output per-residue error probability + error type classification.</p>`,
      approach_zh: `<p>训练 error detector：(1) Plan A 11K (密度, 模型, 标签)；(2) 合成注入错误（交换链 ID、突变残基、移位坐标）；(3) 模型学习区分真实 vs 注入错误；(4) 输出每残基错误概率 + 错误类型分类。</p>`,
      key_challenges: `<p><strong>Challenge: Synthetic error distribution differs from real PDB errors. Solution:</strong>Mixture training + few-shot fine-tuning on documented real PDB errors。curriculum training (easy errors first) curriculum。</p>`,
      key_challenges_zh: `<p><strong>Challenge: Synthetic error distribution differs from real PDB errors. Solution:</strong> Curriculum training (easy errors first, then subtle ones) + few-shot fine-tuning on a curated set of documented real-world PDB errors.</p>`,
      evaluation: `<ul><li>Synthetic error detection: AUC and per-class F1</li><li>Real PDB errors: validated detection on entries with documented misassignments</li><li>False positive rate on clean models</li></ul>`,
      evaluation_zh: `<ul><li>Synthetic errors: AUC, per-class F1</li><li>Real cases: PDB entries with documented errors</li><li>False positive rate on clean models</li></ul>`,
      publication: `<p>🎯 <strong>Target: Nature Communications</strong>. Potential wwPDB integration. <strong>Timeline:</strong> 4-6 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：Nature Communications</strong>. Potential wwPDB integration. <strong>Timeline:</strong> 4-6 months.</p>`,
      impact: `<strong>If successful:</strong> Prevents thousands of erroneous depositions from entering PDB.`,
      impact_zh: `<strong>如果成功：</strong>阻止数千个错误沉积进入 PDB。`,
      tags: ['★★ Sub-journal', 'Error Detection', '4-6 months', 'Nat Commun']
    },
    {
      tier: 'subjournal',
      tier_label_en: '★★ Sub-journal · NeurIPS / Nat Methods',
      tier_label_zh: '★★ 子刊 · NeurIPS / Nat Methods',
      title_en: "Multimodal Cryo-EM Embedding Space (CryoCLIP)",
      title_zh: "多模态冷冻电镜嵌入空间 (CryoCLIP)",
      summary_en: "Build a CLIP-style joint embedding space where (density, sequence, atomic model, QC metrics) align — enabling cross-modal retrieval, missing-modality inference, and zero-shot transfer.",
      summary_zh: "构建 CLIP 式联合嵌入空间，让（密度、序列、原子模型、QC 指标）对齐 —— 支持跨模态检索、缺失模态推断、zero-shot 迁移。",
      problem: `<p>Cryo-EM data exists in multiple modalities (density, atomic model, sequence, QC). Currently each is processed separately. No unified representation — preventing cross-modal queries like "given a density map, find similar sequences".</p>`,
      problem_zh: `<p>冷冻电镜数据存在多模态（密度、原子模型、序列、QC）。每种独立处理。没有统一表示 —— 阻止跨模态查询如"给定密度找相似序列"。</p>`,
      unique_advantage: `<strong>Why ONLY Plan A enables this:</strong> 4-modality (density, sequence, structure, QC) perfectly aligned at entry level requires Plan A. AlphaFold in sequence-structure, ESM in sequence — neither covers density or QC.`,
      unique_advantage_zh: `<strong>为什么只有 Plan A 能支撑：</strong>条目级完美对齐的四模态（密度、序列、结构、QC）需要 Plan A。AlphaFold 在序列-结构，ESM 在序列 —— 都不覆盖密度或 QC。`,
      approach: `<p>Density encoder (3D ViT), Sequence encoder (ESM-2 frozen + adapter), Structure encoder (SE(3) Transformer on CA positions), QC encoder (MLP on PHENIX metrics)。4 encoder output 768  embedding embedding space.Contrastive loss: same-entry 4-modality embeddings should be close。</p>`,
      approach_zh: `<p>Density encoder: 3D ViT; Sequence encoder: ESM-2 frozen + adapter; Structure encoder: SE(3) Transformer on CA; QC encoder: MLP on PHENIX metrics。4 encoders project to shared 768-d embedding space。Contrastive loss: same-entry 4-modality embeddings should be close。</p>`,
      key_challenges: `<p><strong>Challenge: Vast information density gap (100³ voxels vs 200 AA）：</strong><strong>Solution:</strong>Hierarchical pooling hierarchical pooling maps density to sequence-length representation;ESM-2 frozen frozen ESM-2 stabilizes the sequence embedding space.</p>`,
      key_challenges_zh: `<p><strong>Challenge: 密度和序列信息密度差距大：</strong><strong>Solution:</strong>Hierarchical pooling 让密度变成 sequence-length 表示；ESM-2 frozen 让序列空间稳定。</p>`,
      evaluation: `<ul><li>Retrieval accuracy: cross-modal queries</li><li>Cross-modal alignment: embedding similarity ranking consistency</li><li>Downstream zero-shot：CATH/SCOP classification,fold recognition</li></ul>`,
      evaluation_zh: `<ul><li>Retrieval accuracy: query-by-one-modality results in all four modalities</li><li>Cross-modal alignment: embedding similarity ranking consistency across modalities</li><li>Downstream zero-shot: CATH/SCOP classification and fold recognition</li></ul>`,
      publication: `<p>🎯 <strong>Target: NeurIPS / Nature Methods</strong>. Appealing to both ML community and structural biology. <strong>Timeline:</strong> 6-9 months.</p>`,
      publication_zh: `<p>🎯 <strong>目标：NeurIPS / Nature Methods</strong>. Appealing to both ML community and structural biology. <strong>Timeline:</strong> 6-9 months.</p>`,
      impact: `<strong>If successful:</strong> The Rosetta Stone of structural biology AI — query by any modality, get matched answers in all four.`,
      impact_zh: `<strong>如果成功：</strong>结构生物学 AI 的罗塞塔石碑 —— 以任一模态查询，在所有四模态获得对应答案。`,
      tags: ['★★ Sub-journal', 'Multimodal CLIP', '6-9 months', 'NeurIPS / Nat Methods']
    }
  ]
};
